In [5]:
import numpy as np
import pandas as pd

In [6]:
# 1D array
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
# 2D array
n = np.array([[1,2,3,4], [5,6,7,8]])

In [8]:
print(type(n))
n.dtype

<class 'numpy.ndarray'>


dtype('int64')

In [9]:
new_n = np.array(n, dtype=np.int8)
new_n.dtype

dtype('int8')

In [10]:
# fill rows and cols with required value 0
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
# fill rows and cols with required value 12
np.full((4,3), 12)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [12]:
# range
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# range with skip value
np.arange(1,10, 5)

array([1, 6])

In [14]:
# random
np.random.randint(1, 120)

66

In [15]:
# random  with how many random numbers required
np.random.randint(1, 120, 8)

array([104,  83,  85,  17,  11,  81,  29,  12])

In [16]:
# get shape of array
n = np.array([[1,2,3,4], [5,6,7,8]])
n.shape

(2, 4)

In [17]:
# change shape of array
n.shape = (4,2) 
print(n.shape)
print(n)

n.shape = (2,4) 
print(n.shape)
print(n)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [18]:
# vstack vertical stack
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
np.vstack((a1, a2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.equal(np.stack((a1,a2)), np.vstack((a1,a2)))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [20]:
# hstack horizontal stack
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
# column_stack
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
np.column_stack((a1,a2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [22]:
# intersect1d get common in arrays
b1 = np.array([1,2,3,4,5])
b2 = np.array([4,5,6,7])
np.intersect1d(b1, b2)

array([4, 5])

In [23]:
# setdiff1d get unqiue elements in array
c1 = np.array([1,2,3,4])
c2 = np.array([4,1, 5,6])
print(np.setdiff1d(c1,c2)) # get only from c1
print(np.setdiff1d(c2,c1)) # get only from c2

[2 3]
[5 6]


In [24]:
# sum
d1 = np.array([1,2,3,4])
d2 = np.array([1,2,3,4])
d3 = np.array([1,2,3,4])
d4 = np.array([1,2,3,4])
np.sum([d1,d2,d3,d4])

np.int64(40)

In [25]:
# sum by cols
np.sum([d1,d2,d3,d4], axis=0)

array([ 4,  8, 12, 16])

In [26]:
# sum by rows
np.sum([d1,d2,d3,d4], axis=1)

array([10, 10, 10, 10])

In [27]:
# basic scalar operations
e1 = np.array([10,20,30])
print(e1 + 2)
print(e1 - 2)
print(e1 * 2)
print(e1 / 2)

[12 22 32]
[ 8 18 28]
[20 40 60]
[ 5. 10. 15.]


In [28]:
# mean median and standard deviation
e2 = np.array([1,2.5,3,4.3,4.5,5.5,6,7])
print(np.mean(e2))
print(np.median(e2))
print(np.std(e2))

4.225
4.4
1.8518571759182727


In [29]:
f1 = np.array([10,20,30])
f2 = np.array([1,2,3])
print(f1.dot(f2))
print(f2.dot(f1))

140
140


In [30]:
# transpose
g1 = np.array([1,2,3,4])
g2 = np.array([5,6,7,8])
v_stack = np.vstack((g1,g2))
print(v_stack)
np.transpose(v_stack)

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [31]:
# save and load
np.save('saved/nmpy', v_stack)
np.load('saved/nmpy.npy')

FileNotFoundError: [Errno 2] No such file or directory: 'saved/nmpy.npy'

In [19]:
# ndim to get dimension of array
vector = np.array([0, 1,2,3])
matrix = np.array([[0, 1,2,3], [0, 4,5,6]])
print(vector.ndim)
print(matrix.ndim)

1
2


In [20]:
# tensor or 3d array is an array of 2 maxtix (2d array)
matrix1 = np.array([[1,2,3], [4,5,6]])
matrix2 = np.array([[7,8,9], [10,11,12]])

tensor = np.array([matrix1, matrix2])
print(tensor.ndim)
print(tensor)

3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
np.linspace(1,2,100)

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [36]:
np.zeros((1,2)).ndim

2

In [39]:
np.random.rand(10,3)

array([[0.44341211, 0.47017713, 0.52803598],
       [0.87033472, 0.00682157, 0.32127755],
       [0.76063522, 0.39429424, 0.54194708],
       [0.91791476, 0.8503373 , 0.23804229],
       [0.79919777, 0.36657547, 0.41711301],
       [0.03267983, 0.66128388, 0.11479667],
       [0.14037146, 0.64830393, 0.10240977],
       [0.57706236, 0.53090851, 0.5418138 ],
       [0.22841455, 0.3223775 , 0.88089591],
       [0.98143981, 0.43927662, 0.82748536]])

In [64]:
np.random.randint(0,100, 2)

array([25, 25])

In [49]:
np.ones(10, dtype=np.str_)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [53]:
np.empty(10, dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [55]:
np.full(10, 2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [59]:
np.linspace(10, 20, 3)

array([10., 15., 20.])

In [63]:
np.full((1,2,3), 10)

array([[[10, 10, 10],
        [10, 10, 10]]])

In [67]:
np.full(10,6)

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [76]:
a = np.array((0,0))
a.fill(10)
print(a)

[10 10]


In [86]:
a = np.empty(2)
a.fill(10)
a

array([10., 10.])

In [96]:
multi_DArray = np.array( [
                            [
                                [1,2,3,4,5],
                                [5,4,3,2,1]
                            ],
                            [
                                [6,7,8,9,10],
                                [10,9,8,7,6]
                            ] ] )
multi_DArray[0, 1]

array([5, 4, 3, 2, 1])

In [111]:
a = np.array([1,2,3,4])
b = np.insert(a, 4, values=[5,6,7])
c = np.append(b, values=[8,9,10])
print(a, b, c)

[1 2 3 4] [1 2 3 4 5 6 7] [ 1  2  3  4  5  6  7  8  9 10]


In [112]:
np.delete(c, 0)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
d = np.random.randint(0, 10, 4)
print(d)
e = np.sort(d)
print(e)


[6 1 2 0]
[0 1 2 6]


In [119]:
np.copy(e)

array([0, 1, 2, 6])

In [130]:
f = e
f[0] = 11000
print(e.view(), f.view())

[11000     1     2     6] [11000     1     2     6]


In [137]:
a = np.array([[1,2,3], [4,5,6]])
b = a.reshape(3,2)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [149]:
b = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
b = b.reshape(3,2, 2)
print(b)
print(b.flatten())
print(b.ravel())

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [152]:
np.mod(a, a)

array([[0, 0, 0],
       [0, 0, 0]])

In [155]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [5]:
a = np.arange(0, 10).reshape(5,1, 2)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

45
[[20 25]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
a = np.arange(12).reshape(3,2,2)
a[0]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [10]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr[:, 1]

array([2, 5])

In [30]:
arr1 = np.arange(0, 120)
print(arr1.shape)
arr2 = arr1.reshape(40, 1, 3)
print(arr2)
print(arr2.transpose())
print(arr2.shape)

(120,)
[[[  0   1   2]]

 [[  3   4   5]]

 [[  6   7   8]]

 [[  9  10  11]]

 [[ 12  13  14]]

 [[ 15  16  17]]

 [[ 18  19  20]]

 [[ 21  22  23]]

 [[ 24  25  26]]

 [[ 27  28  29]]

 [[ 30  31  32]]

 [[ 33  34  35]]

 [[ 36  37  38]]

 [[ 39  40  41]]

 [[ 42  43  44]]

 [[ 45  46  47]]

 [[ 48  49  50]]

 [[ 51  52  53]]

 [[ 54  55  56]]

 [[ 57  58  59]]

 [[ 60  61  62]]

 [[ 63  64  65]]

 [[ 66  67  68]]

 [[ 69  70  71]]

 [[ 72  73  74]]

 [[ 75  76  77]]

 [[ 78  79  80]]

 [[ 81  82  83]]

 [[ 84  85  86]]

 [[ 87  88  89]]

 [[ 90  91  92]]

 [[ 93  94  95]]

 [[ 96  97  98]]

 [[ 99 100 101]]

 [[102 103 104]]

 [[105 106 107]]

 [[108 109 110]]

 [[111 112 113]]

 [[114 115 116]]

 [[117 118 119]]]
[[[  0   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48
    51  54  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99
   102 105 108 111 114 117]]

 [[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49
    52  55  58  61  64  67  70

In [32]:
df = pd.DataFrame({
    'column1': [1, 2, 3],
    'column2': ['A', 'B', 'C'],
    'column3': [True, False, True]
})
print(df)

   column1 column2  column3
0        1       A     True
1        2       B    False
2        3       C     True


In [35]:
new_df = df[['column1', 'column2']].head()
new_series = df[['column1', 'column2']].head()
print(new_df)
print(new_series)
print(type(new_df))
print(type(new_series))

   column1 column2
0        1       A
1        2       B
2        3       C
   column1 column2
0        1       A
1        2       B
2        3       C
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
